Support for StackExchange.Redis version 2.6.90
mataness/StackExchange.Redis.MultiplexerPool pull request #2
Opened 2023-01-28 21:20 UTC by Treno1

Newer redis versions added GetServers and DisposeAsync functions to IConnectionMultiplexer interface. Added support for these functions for your version of multiplexer

2023-04-23 17:48 UTC, mataness requested changes

2023-04-23 17:48 UTC, mataness commented on samples/RedisConnectionPoolConsoleApp/RedisConnectionPoolConsoleApp.csproj
> +  <ItemGroup>
why this dependency is required ?

2023-04-23 17:48 UTC, mataness commented on tests/StackExchange.Redis.MultiplexerPool.Tests/StackExchange.Redis.MultiplexerPool.Tests.csproj
> +    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="5.0.0" />
why this dependency is required ?

2023-04-23 17:48 UTC, mataness commented on src/StackExchange.Redis.MultiplexerPool/Multiplexers/InternalDisposableConnectionMultiplexer.cs
> +        public ValueTask DisposeAsync()
I am pretty sure that this will cause unobserved task exception, can you add a UT and check it ?

2023-09-13 08:48 UTC, Treno1 commented
Sorry, forgot about this PR. Thanks for implementing it!

2023-09-13 08:48 UTC, closed without merging